name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: |
          rm -f package-lock.json
          npm install

      - name: Debug Environment
        run: |
          echo "Checking environment variables:"
          echo "NEXT_PUBLIC_API_URL exists: ${{ !!secrets.NEXT_PUBLIC_API_URL }}"
          echo "GOOGLE_CLIENT_EMAIL exists: ${{ !!secrets.GOOGLE_CLIENT_EMAIL }}"
          echo "GOOGLE_PRIVATE_KEY exists: ${{ !!secrets.GOOGLE_PRIVATE_KEY }}"
          echo "GOOGLE_DRIVE_FOLDER_ID exists: ${{ !!secrets.GOOGLE_DRIVE_FOLDER_ID }}"

      - name: Build
        run: npm run build
        env:
          NEXT_PUBLIC_API_URL: ${{ secrets.NEXT_PUBLIC_API_URL }}
          GOOGLE_CLIENT_EMAIL: ${{ secrets.GOOGLE_CLIENT_EMAIL }}
          GOOGLE_PRIVATE_KEY: ${{ secrets.GOOGLE_PRIVATE_KEY }}
          GOOGLE_DRIVE_FOLDER_ID: ${{ secrets.GOOGLE_DRIVE_FOLDER_ID }}
          NODE_ENV: production

      - name: Add .nojekyll file
        run: touch ./out/.nojekyll

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./out
          force_orphan: true 